"""
This script deletes all files generated by the running web server (except Python cache directories).
Database files, log files, and miscellaneous cache files are removed.
Run this and 'clear_cache.py' to reset the web server during development.

NEVER RUN THIS SCRIPT ON A PRODUCTION SERVER!!!  THIS OPERATION IS PERMANENT!!!

Make sure you have a backup of any important information.
"""

import os
import shutil
import subprocess
import sys


this_dir: str = os.path.dirname(__file__)


def remove(*relative_path: str) -> None:
    path: str = os.path.join(this_dir, *relative_path)
    try:
        if os.path.isdir(path):
            shutil.rmtree(path)
        else:
            os.remove(path)
    except OSError as error:
        print(error, file=sys.stderr)


def main() -> None:
    response_1 = input(
        "-------------------------------------------------------------------------------\n"
        + "NEVER RUN THIS SCRIPT ON A PRODUCTION SERVER!!!  THIS OPERATION IS PERMANENT!!!\n"
        + "-------------------------------------------------------------------------------\n"
        + "\n"
        + "Are you sure you want to delete all databases, log files, and cache files?\n"
        + "(y/N): "
    )
    if not response_1.lower().startswith("y"):
        print("cancelled")
        return

    response_2 = input(
        "\n"
        + "Are you absolutely sure that you want to delete ALL DATABASES?\n"
        + "(y/N): "
    )
    if not response_2.lower().startswith("y"):
        print("cancelled")
        return

    # Log files
    print("removing logs...")
    remove("skr", "flaskapp", "logs")

    # Miscellaneous cache files
    print("removing miscellaneous cache files...")
    remove("skr", "flaskapp", "default_login.json")

    # Database files
    print("removing databases...")
    db_dir: str = os.path.join("skr", "flaskapp", "db")
    for file in os.listdir(os.path.join(this_dir, db_dir)):
        if file == "README":
            continue
        remove(db_dir, file)

    print("done")


if __name__ == "__main__":
    main()
